// <auto-generated />
using System;
using AuditDataPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditDataPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913140148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Column")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("ImportRowId");

                    b.HasIndex("RuleId");

                    b.ToTable("Findings", (string)null);
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.ToTable("ImportJobs", (string)null);
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasFindings")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows", (string)null);
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RuleSets", (string)null);
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.Finding", b =>
                {
                    b.HasOne("AuditDataPlatform.Domain.Entities.ImportJob", "ImportJob")
                        .WithMany("Findings")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditDataPlatform.Domain.Entities.ImportRow", "ImportRow")
                        .WithMany("Findings")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditDataPlatform.Domain.Entities.Rule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportJob");

                    b.Navigation("ImportRow");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("AuditDataPlatform.Domain.Entities.RuleSet", "RuleSet")
                        .WithMany("ImportJobs")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportRow", b =>
                {
                    b.HasOne("AuditDataPlatform.Domain.Entities.ImportJob", "ImportJob")
                        .WithMany("ImportRows")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.Rule", b =>
                {
                    b.HasOne("AuditDataPlatform.Domain.Entities.RuleSet", "RuleSet")
                        .WithMany("Rules")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportJob", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("ImportRows");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.ImportRow", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("AuditDataPlatform.Domain.Entities.RuleSet", b =>
                {
                    b.Navigation("ImportJobs");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
